[workspace]
members = [
  "chaos_theory",
  "chaos_theory_derive",
  "experimental/chaos_theory_core",
  "experimental/chaos_theory_v2",
  "xtask",
]
exclude = ["chaos_theory_example", "chaos_theory_example_fuzz"]
resolver = "2"

[profile.dev]
opt-level = 1
debug = false

[workspace.package]
version = "0.5.0"
authors = ["Gregory Petrosyan <pgregory@pgregory.net>"]
homepage = "https://github.com/flyingmutant/chaos_theory"
repository = "https://github.com/flyingmutant/chaos_theory"
documentation = "https://docs.rs/chaos_theory"
categories = [
  "development-tools::testing",
  "rust-patterns",
]
keywords = [
  "random",
  "property-testing",
  "fuzzing",
  "quickcheck",
  "hypothesis",
]
license = "MPL-2.0"
edition = "2024"

# TODO: update this list
[workspace.lints]
rust.unsafe_code = "forbid"
rust.dead_code = "warn"
rust.missing_docs = "warn"
rust.unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }  # https://github.com/rust-fuzz/cargo-fuzz/issues/372
rustdoc.missing_crate_level_docs = "warn"
clippy.alloc_instead_of_core = "warn"
clippy.allow_attributes = "warn"
clippy.clone_on_ref_ptr = "warn"
clippy.deref_by_slicing = "warn"
clippy.std_instead_of_alloc = "warn"
clippy.std_instead_of_core = "warn"
clippy.str_to_string = "warn"
clippy.suboptimal_flops = "warn"
clippy.unnecessary_self_imports = "warn"
clippy.unused_trait_names = "warn"
clippy.unwrap_used = "warn"
clippy.use_self = "warn"
clippy.all = { level = "warn", priority = 0 }
clippy.pedantic = { level = "warn", priority = 0 }
clippy.cast_possible_truncation = { level = "allow", priority = 2 } # mostly noise
clippy.cast_possible_wrap = { level = "allow", priority = 2 }       # mostly noise
clippy.cast_precision_loss = { level = "allow", priority = 2 }      # mostly noise
clippy.cast_sign_loss = { level = "allow", priority = 2 }           # mostly noise
clippy.test_attr_in_doctest = { level = "allow", priority = 2 }     # we do want to show tests in doc comments
clippy.unreadable_literal = { level = "allow", priority = 2 }       # easier to cross-reference magic constants

[workspace.dependencies]
anyhow = "1.0.98"
bstr = { version = "1.13.1", default-features = false }
bytes = { version = "1.12.1", default-features = false }
clap = "4.5.37"
ecow = { version = "0.2.6", default-features = false }
either = { version = "1.18.0", default-features = false }
env_logger = "0.11.8"
hashbrown = { version = "0.17.1", default-features = false }
indexmap = { version = "2.14.1", default-features = false }
jiff = { version = "0.2.35", default-features = false }
jiff-tzdb = "=0.1.8"
libfuzzer-sys = { package = "chaos_theory_libfuzzer", version = "0.4.13" }
libm = "0.2.16"
log = "0.4.27"
ordered-float = { version = "5.5.0", default-features = false }
ordermap = { version = "1.2.1", default-features = false }
prettyplease = "0.2"
proc-macro2 = "1.0"
quote = "1.0"
regex = { version = "1.11.1", default-features = false }
regex-syntax = { version = "0.8.5", default-features = false }
serde_json = { version = "1.0.149", default-features = false }
syn = { version = "2.0", default-features = false }
tinyvec = { version = "1.10.0", default-features = false }
xshell = "0.2.6"
uuid = { version = "1.22.0", default-features = false }

chaos_theory_core = { path = "experimental/chaos_theory_core" }
chaos_theory_derive = { version = "0.5.0", path = "chaos_theory_derive" }
