[package]
name = "chaos_theory_v2"
description = "Version of chaos_theory built on top of chaos_theory_core"
publish = false

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
all = []

[dependencies]
chaos_theory_core.workspace = true
